version: '2'

services:
  zeo:
    build: ./plone
    command: ["/plone/bin/zeo", "fg"]
    environment:
      - ZEO_PORT=8100
    expose:
      - "8100"

  plone:
    build: ./plone
    image: pyrenees_plone
    command: ["/plone/bin/instance", "fg"]
    environment:
      - ZEO_HOST=zeo
      - ZEO_PORT=8100
    ports:
      - "9080:8080"

  restapi:
    build: ./restapi
    depends_on:
      - plone
    ports:
      - "9081:8080"


