version: '2'

services:

  server:
    build: ./server
    depends_on:
    - oauth
    - elastic
    ports:
      - "9080:8080"

  client:
    build: ./client
    ports:
      - "3000:3000"

  elastic:
   image: elasticsearch:2.3.3
   expose:
   - "9200"

  oauth:
    extends: 
      file: oauth/oauth-compose.yml
      service: oauth
    links:
    - redis
    - ldap
    ports:
      - "6543:6543"
  ldap:
    extends: 
      file: oauth/oauth-compose.yml
      service: ldap
  redis:
    extends: 
      file: oauth/oauth-compose.yml
      service: redis
