version: '2'

services:

  oauth:
    image: plone/plone.oauth:latest
    depends_on:
    - redis
    - ldap
    ports:
    - "6543:6543"
    environment:
    - JWTSECRET=secret
    - LDAP_PROFILE=["person","inetOrgPerson"]
    - LDAP_USER_FILTER=mail={username},ou=Users,dc=plone,dc=com
    - LDAP_ROOT_DN=uid=admin,ou=system
    - LDAP_ROOT_PW=secret
    - LDAP_BASE_DN=dc=plone,dc=com
  redis:
    image: redis
    volumes:
    - ./volumes/redis:/data
    expose:
    - "6379"  
  ldap:
    image: greggigon/apacheds
    volumes:
    - ./volumes/ldap:/data
    - ./volumes/ldap-bootstrap:/bootstrap
    expose:
    - "10389"
    environment:
    - BOOTSTRAP_FILE=/bootstrap/demo.ldif
    restart: always
  elasticsearch:
     image: elasticsearch:2.3.3
     expose:
     - "9200"
  ploneserver:
    image: plone/plone.server:latest
    depends_on:
    - oauth
    - elasticsearch
    volumes:
    - ./data:/app/data
    ports:
    - "8080:8080"
    environment:
    - JWTSECRET=secret
    - JWTALGORITHM=HS256
    - CLIENTID=plone
    - CLIENTPASSWORD=plone
  ploneclient:
    image: plone/plone_client:latest
    depends_on:
    - oauth
    - ploneserver
    ports:
    - "3000:3000"