apiVersion: v1
kind: Service
metadata:
  name: ploneng
  labels:
    app: ploneng
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: ploneng
---
apiVersion: v1
kind: Service
metadata:
  name: oauth
  labels:
    app: ploneng
spec:
  type: NodePort
  ports:
  - port: 6543
    targetPort: 6543
  selector:
    app: ploneng
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: ploneng
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: ploneng
---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    app: ploneng
spec:
  ports:
  - port: 10389
    targetPort: 10389
  selector:
    app: ploneng
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: ploneng
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: ploneng